# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Service
metadata:
  name: pkg-mgr-db-svc
  labels:
    app: pkg-mgr
spec:
  ports:
  - port: 3306
  selector:
    app: pkg-mgr
    tier: db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: pkg-mgr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkg-mgr-db
  labels:
    app: pkg-mgr
spec:
  selector:
    matchLabels:
      app: pkg-mgr
      tier: db
  strategy:
    type: Recreate
    template:
      metadata:
        labels:
          app: pkg-mgr
          tier: db
      spec:
        containers:
        - image: mariadb:10.1.38
          name: mariadb
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: root-db-password
                key: password
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: password
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: pkg-mgr-config
                key: DB_USERNAME
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: pkg-mgr-config
                key: DB_NAME
          ports:
          - containerPort: 3306
            name: mariadb
          volumeMounts:
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mysql
        volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim