# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Service
metadata:
  name: pkg-mgr-api-svc
  labels:
    app: pkg-mgr
spec:
  ports:
    - port: 80
  selector:
    app: pkg-mgr
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkg-mgr-app
  labels:
    app: pkg-mgr
spec:
  selector:
    matchLabels:
      app: pkg-mgr
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pkg-mgr
        tier: frontend
    spec:
      volumes:
      - name: pkg-volume
        hostPath:
          path: ../../
          type: Directory
      initContainers:
      - image: electrocucaracha/pkg_mgr
        name: pkg-mgr-init
        command:
        - init
        env:
        - name: PKG_DB_HOSTNAME
          value: pkg-mgr-db-svc
        - name: PKG_SQL_ENGINE
          value: mysql
        - name: PKG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
        - name: PKG_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: pkg-mgr-config
              key: DB_USERNAME
        - name: PKG_DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: pkg-mgr-config
              key: DB_NAME
        - name: PKG_SCRIPTS_PATH
          value: /pkg/scripts
        - name: PKG_MAIN_FILE
          value: /pkg/install.sh
        volumeMounts:
        - mountPath: /pkg
          name: pkg-volume
      containers:
      - image: electrocucaracha/pkg_mgr
        name: pkg-mgr-api
        command:
        - serve
        env:
        - name: PKG_DB_HOSTNAME
          value: pkg-mgr-db-svc
        - name: PKG_SQL_ENGINE
          value: mysql
        - name: PKG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
        - name: PKG_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: pkg-mgr-config
              key: DB_USERNAME
        - name: PKG_DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: pkg-mgr-config
              key: DB_NAME
        ports:
        - containerPort: 80
          name: pkg-mgr